### PR TITLE
modified labelSelector check

### LINKED ISSUE #32: tenant owner has access to all namespaces
# Bug description
The tenant owner has access to all namespaces

# How to reproduce

1. ns-filter installed
2. as tenant admin, issue the following:
`curl -k https://ns-filter:9001/api/v1/namespaces?labelSelector -H "Authorization: Bearer $TOKEN"`
3. tenant owner gets the complete list of all namespaces

# Expected behavior
The tenant owner can see its own namespaces only

# Logs
```
2020-11-04T17:41:00.412+0100    LEVEL(-2)       namespace_filter        Decorating request for Namespace filtering
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        Getting user from request       {"username": "alice", "groups": ["capsule.clastix.io", "spectre"]}
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        Tenants list    {"owner": "User", "name": "alice", "tenants": ["oil", "gas"]}
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        Tenants list    {"owner": "Group", "name": "capsule.clastix.io", "tenants": []}
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        Tenants list    {"owner": "Group", "name": "spectre", "tenants": ["spectre"]}
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        RawQuery        {"q": {"labelSelector":[""]}}
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        labelSelector added     {"selector": "capsule.clastix.io/tenant in (gas,oil,spectre)"}
2020-11-04T17:41:00.412+0100    LEVEL(-4)       namespace_filter        updating RawQuery       {"query": "labelSelector=&labelSelector=capsule.clastix.io%2Ftenant+in+%28gas%2Coil%2Cspectre%29"}
```
Please, note `{"query": "labelSelector=&labelSelector=capsule.clastix.io%2Ftenant+in+%28gas%2Coil%2Cspectre%29"}`

# Additional context

- Capsule version: v0.0.1
- ns-filter version: latest
- Kubernetes version: v1.19

### PR DESCRIPTION
**Pull request by bsctl**
@prometherion, modified labelSelector check to fix #32. Please review.

### CODE REVIEW

File: internal/webserver/webserver.go [hunk 1]
```diff
@@ -150,7 +150,7 @@ func (n kubeFilter) namespacesHandler(writer http.ResponseWriter, request *http.
 		q.Set("labelSelector", v)
 		log.V(4).Info("labelSelector updated", "selector", v)
 	} else {
-		q.Add("labelSelector", s.String())
+		q.Set("labelSelector", s.String())
```
Comment (prometherion) [inline internal/webserver/webserver.go:153]: What's the rationale behind the `Set` rather than `Add`?

Comment (bsctl) [reply internal/webserver/webserver.go:153]: My understanding is:

- `Set` sets the key to value. It replaces any existing values.
  The original query `{"query": "labelSelector"}` becomes `{"query": "labelSelector=capsule.clastix.io%2Ftenant+in+%28gas%2Coil%2Cspectre%29"}`

- `Add` adds the value to key. It appends to any existing values associated with key.
  The original query `{"query": "labelSelector"}` becomes `{"query": "labelSelector=&labelSelector=capsule.clastix.io%2Ftenant+in+%28gas%2Coil%2Cspectre%29"}`

The latter is executed as an OR and hence all the namespaces are returned

**Review by prometherion — APPROVED** [review]
LGTM
